---
version: '3'
services:
  test:
    image: kingwings/dependencies
    container_name: king-test
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run test
volumes:
  node_modules: {}
