---
version: '3'
services:
  dev:
    build: .
    image: mhygroupinc/kings-dependencies
    container_name: kings-dev-hot
    ports:
      - '8081:8081'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
volumes:
  node_modules: {}
