---
version: '0'
services:
  dev:
    image: mhygroupinc/kings-dependencies
    container_name: kings-dev-hot
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
volumes:
  node_modules: {}
